/** Minimal persistent data of a player. Everything else lives only in memory. */
export interface PlayerData {
  /** Secret, stable id generated by the browser (never shown to other players). */
  playerId: string;
  /** Public code to share with friends, e.g. FRIEND-83K2. */
  friendCode: string;
  displayName: string;
  character: number;
  /** Global world coordinates (metres) and facing. */
  lastPosition: { x: number; y: number; z: number } | null;
  lastRotation: number;
  /** Summon definition ids the player owns, and the one currently selected. */
  ownedSummons: string[];
  activeSummonId: string | null;
  /** Free summons left today, and the day (UTC yyyy-mm-dd) the counter refers to. */
  freeSummons: { day: string; used: number };
  /** Accepted friends and pending requests (playerIds). */
  friends: string[];
  incomingRequests: string[];
  outgoingRequests: string[];
  lastSeen: number;
}

/** Storage backend. The JSON-file implementation can later be swapped for SQLite/Postgres. */
export interface PlayerDataStore {
  get(playerId: string): PlayerData | undefined;
  findByFriendCode(code: string): PlayerData | undefined;
  put(data: PlayerData): void;
  /** Persist pending changes now. */
  flush(): Promise<void>;
  flushSync(): void;
}
