/**
 * Network protocol shared by client and server. The Colyseus state schema
 * itself lives in the server (server/src/rooms/schema.ts) and is mirrored on
 * the client through Colyseus' reflection.
 */
import { hashString } from './math/rng.ts';

export const ROOM_NAME = 'world';
export const DEFAULT_SERVER_PORT = 2567;

export enum MsgType {
  /** client → server: InputPacket */
  Input = 'i',
  /** client → server: string ; server → clients: ChatMessage */
  Chat = 'c',
  /** client → server: Emote */
  Emote = 'e',
  /** server → owner: OwnProfile */
  Profile = 'profile',
  /** client → server: SummonRequest */
  Summon = 'sm',
  /** server → owner: CollectionInfo */
  Collection = 'col',
  /** client → server: target reference ("p:<sessionId>", "s:<ownerSessionId>" or "") */
  Target = 'tg',
  /** client → server: ability index 0..3 (0 = basic attack order) */
  Ability = 'ab',
  /** server → all: AbilityEvent */
  AbilityFx = 'fx',
  /** server → all: DamageEvent */
  Damage = 'dmg',
  /** server → all: DeathEvent */
  Death = 'death',
  /** client → server: FriendRequest */
  Friend = 'fr',
  /** server → player: FriendsInfo */
  Friends = 'friends',
  /** server → player: FriendFeedback */
  FriendFeedback = 'frfb',
  /** player → server: boolean, true = get on the mount, false = get off (validated by the server). */
  Mount = 'mt',
}

/** Emotes, played with KayKit animations. Cancelled as soon as the character moves. */
export enum Emote {
  None = 0,
  Cheer = 1,
  Sit = 2,
  Lie = 3,
}
export const EMOTE_COUNT = 4;

/** Options sent with joinOrCreate. Everything is validated by the server. */
export interface JoinOptions {
  /** Stable secret id generated by the browser (see client/src/game/identity.ts). */
  playerId?: string;
  name?: string;
  character?: number;
}

/** Private data sent only to its owner after joining (server → client 'profile'). */
export interface OwnProfile {
  friendCode: string;
  displayName: string;
  /** True when the player was restored at its saved position. */
  restored: boolean;
}

export interface ChatMessage {
  /** Session id of the author. */
  id: string;
  name: string;
  text: string;
}

export const NAME_MAX_LENGTH = 16;
export const CHAT_MAX_LENGTH = 140;

/** Removes control characters, collapses spaces, trims and truncates. */
function cleanText(raw: unknown, max: number): string {
  if (typeof raw !== 'string') return '';
  // eslint-disable-next-line no-control-regex
  return raw.replace(/[\u0000-\u001f\u007f-\u009f\u200b-\u200f\u2028-\u202e]/g, '').replace(/\s+/g, ' ').trim().slice(0, max);
}

export function sanitizeName(raw: unknown): string {
  return cleanText(raw, NAME_MAX_LENGTH);
}

export function sanitizeChat(raw: unknown): string {
  return cleanText(raw, CHAT_MAX_LENGTH);
}

export enum Anim {
  Idle = 0,
  Walk = 1,
  Run = 2,
  Jump = 3,
}

export const INPUT_AXIS_MAX = 127;

/** One simulation tick of player intent. The client never sends positions. */
export interface PlayerInput {
  /** Sequence number, increases by one per tick. */
  seq: number;
  /** Desired horizontal direction in world space, quantised to [-127, 127]. */
  mx: number;
  mz: number;
  run: boolean;
  jump: boolean;
}

/** Compact wire form: [seq, mx, mz, flags]. */
export type InputPacket = [number, number, number, number];

export function encodeInput(i: PlayerInput): InputPacket {
  return [i.seq, i.mx, i.mz, (i.run ? 1 : 0) | (i.jump ? 2 : 0)];
}

export function decodeInput(p: unknown): PlayerInput | null {
  if (!Array.isArray(p) || p.length !== 4 || !p.every((v) => typeof v === 'number' && Number.isFinite(v))) return null;
  return { seq: p[0], mx: p[1], mz: p[2], run: (p[3] & 1) !== 0, jump: (p[3] & 2) !== 0 };
}

/** KayKit Adventurers characters available in the free tier (files in client/public/assets/characters). */
export const CHARACTERS = ['Knight', 'Barbarian', 'Mage', 'Rogue', 'Rogue_Hooded'] as const;
export type CharacterName = (typeof CHARACTERS)[number];

/** Deterministic character choice from a session id. */
export function characterForSession(sessionId: string): number {
  return hashString(sessionId) % CHARACTERS.length;
}

// ------------------------------------------------------------------ summons

/** AI state of a summon (server state machine). */
export enum SummonMode {
  Spawning = 0,
  Idle = 1,
  Follow = 2,
  Attack = 3,
  Return = 4,
  Dead = 5,
}

/** Animation slot currently played by a summon; one-shots restart when `actionSeq` changes. */
export const SUMMON_ACTIONS = ['idle', 'walk', 'run', 'attack', 'special', 'hit', 'death', 'spawn', 'cheer'] as const;
export type SummonAction = (typeof SUMMON_ACTIONS)[number];

export type SummonRequest =
  | { op: 'call' }
  | { op: 'dismiss' }
  | { op: 'select'; id: string }
  | { op: 'draw' };

/** server → owner: the player's collection (sent after joining and after each change). */
export interface CollectionInfo {
  owned: string[];
  active: string | null;
  freeLeft: number;
  /** Result of the last free summon, if this message answers one. */
  draw?: { id: string; isNew: boolean };
  /** Seconds before the summon can be called again (after its death). */
  recallIn?: number;
}

export const SUMMON_RECALL_DELAY = 8;

// ------------------------------------------------------------------ combat

export const PLAYER_MAX_HP = 100;
export const PLAYER_RESPAWN_DELAY = 4;
/** An owner can only target things this close to him (metres). */
export const TARGET_RANGE = 40;

/** Something that can be hit: a player or a summon (identified by its owner). */
export type TargetRef = `p:${string}` | `s:${string}`;

export interface AbilityEvent {
  /** Owner of the summon using the ability. */
  owner: string;
  summon: string;
  ability: number;
  type: string;
  vfx: string;
  sound: string;
  cooldown: number;
  from: { x: number; y: number; z: number };
  target: string;
  /** Projectiles: flight time in seconds. */
  flight?: number;
  /** AoE radius. */
  radius?: number;
}

export interface DamageEvent {
  target: string;
  amount: number;
  hp: number;
  maxHp: number;
  x: number; y: number; z: number;
  /** Owner of the attacking summon. */
  by: string;
}

export interface DeathEvent {
  target: string;
  by: string;
  victimName: string;
  killerName: string;
}

/** Damage after the attacker's attack stat and the target's defense. */
export function computeDamage(base: number, attack: number, defense: number): number {
  return Math.max(1, Math.round(base * (attack / 10) * (100 / (100 + Math.max(0, defense)))));
}

// ------------------------------------------------------------------ friends

export type FriendRequest =
  | { op: 'list' }
  | { op: 'add'; code: string }
  | { op: 'accept'; code: string }
  | { op: 'decline'; code: string }
  | { op: 'remove'; code: string }
  | { op: 'join'; code: string };

/** What a player may know about a friend (never the private playerId, never a position). */
export interface FriendInfo {
  code: string;
  name: string;
  status: 'friend' | 'incoming' | 'outgoing';
  online: boolean;
  /** ms timestamp, only for friends. */
  lastSeen?: number;
}

export interface FriendsInfo {
  myCode: string;
  friends: FriendInfo[];
}

export interface FriendFeedback {
  ok: boolean;
  text: string;
}

export const FRIEND_CODE_RE = /^FRIEND-[A-Z2-9]{4}$/;
export const MAX_FRIENDS = 50;
export const JOIN_FRIEND_COOLDOWN = 10;
